[package]
name = "fuyao-guard"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
fuyao-api = { path = "../fuyao-api" }
fuyao-hooks = { path = "../fuyao-hooks" }
tokio = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
