[package]
name = "fuyao-tools"
version.workspace = true
edition.workspace = true

[dependencies]
fuyao-api = { path = "../fuyao-api" }
fuyao-prompt = { path = "../fuyao-prompt" }
fuyao-skills = { path = "../fuyao-skills" }
fuyao-session = { path = "../fuyao-session" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
fancy-regex = { workspace = true }
similar = { workspace = true }
strsim = { workspace = true }
unicode-normalization = { workspace = true }
glob = { workspace = true }
grep-regex = { workspace = true }
grep-searcher = { workspace = true }
ignore = { workspace = true }
encoding_rs = { workspace = true }
libc = { workspace = true }
url.workspace = true
htmd.workspace = true
reqwest.workspace = true
scraper.workspace = true
tracing.workspace = true
